#!/bin/bash

pkg update -y
pkg upgrade -y
pkg install -y x11-repo
pkg install -y tur-repo

pkg install -y fontconfig
pkg install -y freetype
pkg install -y git
pkg install -y gnutls
pkg install -y libandroid-shmem-static
pkg install -y libx11
pkg install -y xorgproto
pkg install -y libdrm
pkg install -y libpixman
pkg install -y libjpeg-turbo
pkg install -y libgmp
pkg install -y libgnutls
pkg install -y mesa-demos
pkg install -y osmesa
pkg install -y pulseaudio
pkg install -y termux-x11-nightly
pkg install -y vulkan-tools
pkg install -y xtrans
pkg install -y libxxf86vm
pkg install -y xorg-xrandr
pkg install -y xorg-font-util
pkg install -y xorg-util-macros
pkg install -y libxfont2
pkg install -y libxkbfile
pkg install -y libpciaccess
pkg install -y xcb-util-renderutil
pkg install -y xcb-util-image
pkg install -y xcb-util-keysyms
pkg install -y xcb-util-wm
pkg install -y xorg-xkbcomp
pkg install -y xkeyboard-config
pkg install -y libxdamage
pkg install -y libxinerama
pkg install -y libxshmfence
pkg install -y libandroid-spawn
pkg install -y libxcb
pkg install -y libxcomposite
pkg install -y libxcursor
pkg install -y libxfixes
pkg install -y libxrender

pkg install -y vulkan-loader-android
pkg install -y mesa-zink
pkg install -y mesa-vulkan-icd-freedreno
pkg install -y mesa
pkg install -y wget

termux-setup-storage

wget https://github.com/alexvorxx/hangover-termux/releases/download/9.22-v1/wine_hangover_9.22_bionic_build_patched.tar.xz

tar -xvf wine_hangover_9.22_bionic_build_patched.tar.xz

cat << 'EOF' > start.sh
#!/bin/bash
echo "Starting YebanOS..."
sleep 1

export LD_LIBRARY_PATH=$PREFIX/lib
termux-x11 :0 &>/dev/null &
sleep 2

export DISPLAY=:0
export GALLIUM_DRIVER=zink
export MESA_LOADER_DRIVER_OVERRIDE=zink
export WINEESYNC_TERMUX=1
export WINEESYNC=1

~/wine_hangover/arm64-v8a/bin/wine explorer /desktop=shell explorer
EOF

chmod +x start.sh
