#!/bin/bash

termux-setup-storage

read -p "Do you want to proceed with the installation? (y/N) " -n 1 -r
echo
if [[ $REPLY != "y" && $REPLY != "Y" ]]; then
    echo "Installation aborted."
    exit 1
fi

echo "Updating packages..."
pkg update -y
pkg upgrade -y

echo "Installing packages..."
pkg install x11-repo -y
pkg install pulseaudio -y
pkg install xwayland -y
pkg install wget -y
pkg install tsu -y
pkg install root-repo -y
pkg install patchelf -y
pkg install p7zip -y
pkg install xorg-xrandr -y
pkg install ncurses-utils -y
pkg install hashdeep -y
pkg install git -y
pkg install tar -y
pkg install glibc-repo -y
pkg install mesa -y
pkg install xfce4 -y
pkg install mesa-zink -y
pkg install virglrenderer-mesa-zink -y
pkg install vulkan-loader-android -y
pkg install virglrenderer-android -y
pkg install android-tools -y
pkg install python-tkinter -y
pkg install xfce4-whiskermenu-plugin -y
pkg install xfce4-screenshooter -y
pkg install xfce4-taskmanager -y
pkg install xfce4-docklike-plugin -y
pkg install matchbox-keyboard -y
pkg install termux-x11-nightly -y

if [ ! -d "$PREFIX/glibc" ]; then
    echo "Downloading and extracting glibc..."
    cd "$PREFIX"
    wget -O glibc.tar.xz "https://github.com/shephard-dev/Emulator/releases/download/assets/glibc.tar.xz"
    tar -xf glibc.tar.xz
    rm glibc.tar.xz
fi

mkdir -p "$PREFIX/Downloads"
cd "$PREFIX/Downloads"
wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/termux_native/mobox_run.sh
chmod +x mobox_run.sh

mkdir -p ~/Desktop
cd ~/Desktop
wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/termux_native/MoboxExplorer.desktop
cd ~

chmod +x "$PREFIX/glibc/opt/scripts/yebanos"
ln -sf "$PREFIX/glibc/opt/scripts/yebanos" "$PREFIX/bin/yebanos"

echo "Installation complete! Type 'yebanos' to start."
